# Use the official GCC image
FROM gcc:latest

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy the C++ source file from the host machine to the container
COPY . .

# Command to compile and run the C++ program
CMD ["bash", "-c", "g++ -o main main.cpp && ./main"]
